
nodeLinker: pnp

npmScopes:
  layerzerolabs:
    npmAuthToken: "${NPM_TOKEN-}"
    npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@gnosis.pm/safe-core-sdk-utils@*":
    dependencies:
      "@ethersproject/bignumber": ^5.7.0
  "@gnosis.pm/safe-core-sdk@*":
    dependencies:
      "@ethersproject/bignumber": ^5.7.0
      "@ethersproject/bytes": ^5.7.0
  "@gnosis.pm/safe-ethers-lib@*":
    dependencies:
      "@ethersproject/abi": ^5.7.0
      "@ethersproject/abstract-signer": ^5.7.0
      "@ethersproject/bignumber": ^5.7.0
      "@ethersproject/providers": ^5.7.0
  "@nomiclabs/hardhat-waffle@*":
    dependencies:
      "@ethereum-waffle/chai": ^4.0.10
      "@ethereum-waffle/provider": ^4.0.5
  "@resolver-engine/imports-fs@*":
    dependencies:
      "@resolver-engine/core": ^0.3.3
  hardhat-deploy@*:
    dependencies:
      "@ethersproject/abi": ^5.7.0
      "@ethersproject/address": ^5.7.0
      "@ethersproject/bignumber": ^5.7.0
      "@ethersproject/bytes": ^5.7.0
      "@ethersproject/constants": ^5.7.0
      "@ethersproject/contracts": ^5.7.0
      "@ethersproject/hash": ^5.7.0
      "@ethersproject/providers": ^5.7.0
      "@ethersproject/solidity": ^5.7.0
      "@ethersproject/transactions": ^5.7.0
      "@ethersproject/wallet": ^5.7.0
      ethers: ^5.7.0
      hardhat: ^2.9.0
  hardhat@*:
    dependencies:
      ethers: ^5.7.0
  mocha@*:
    dependencies:
      eth-gas-reporter: ^0.2.25
  ts-command-line-args@*:
    peerDependencies:
      typescript: ^4.0.0
  zksync-web3@*:
    dependencies:
      "@ethersproject/abi": ^5.7.0
      "@ethersproject/abstract-provider": ^5.7.0
      "@ethersproject/abstract-signer": ^5.7.0
      "@ethersproject/bytes": ^5.7.0
      "@ethersproject/contracts": ^5.7.0
      "@ethersproject/hash": ^5.7.0
      "@ethersproject/json-wallets": ^5.7.0
      "@ethersproject/providers": ^5.7.0
      "@ethersproject/web": ^5.7.0
  "@nomicfoundation/ethereumjs-statemanager@*":
    dependencies:
      "@nomicfoundation/ethereumjs-trie": ^6.0.1
      "@nomicfoundation/ethereumjs-util": ^9.0.1

plugins:
  - path: .yarn/plugins/plugin-envs.cjs
    spec: "https://raw.githubusercontent.com/Ayc0/yarn-plugin-envs/v0.0.3/src/index.js"
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.3.1/bundles/@yarnpkg/plugin-after-install.js"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"
  - path: .yarn/plugins/@yarnpkg/plugin-ensure-version.js
  - path: .yarn/plugins/@yarnpkg/plugin-forge.js

yarnPath: .yarn/releases/yarn-3.6.0.cjs
